### ISSUE TITLE
Remove mask gives error

### ISSUE THREAD

**Issue by saransh13** [HEXRD/hexrdgui#1012]
After loading an image and drawing masks in polar view, the remove mask option in Edit > Manage masks works fine. However, if a new image is loaded after removing all the old masks and adding new ones, the the remove mask button produces the following error

![Screen Shot 2021-08-10 at 11 34 45 AM](https://user-images.githubusercontent.com/15834451/129654445-bb223b27-9bef-4d47-99e8-f3e9cd76a9c5.png)

**Comment by bnmajor** [comment]
@saransh13 Could you provide the exact steps that you took when you saw this error? So far I have been unable to reproduce this.

**Comment by saransh13** [comment]
Ok trying to create a gif/video with this. I will upload shortly. Sometimes, it takes a few rounds of image reloads to reproduce this error.

**Comment by bnmajor** [comment]
Thanks @saransh13! So there is an assumption being made for both toggled and removed masks that when the widget is clicked the `currentRow` is updated accordingly, and this value is what is used to determine which mask to hide/show/remove. This behavior is not guaranteed though, and I think that is what is causing this bug. I still have not been able to reproduce this locally but I think I have a solution and I will tag you in the PR when I have that up.

To note: At this point I believe that this and #1013 are caused by the same bad assumption.
