### ISSUE TITLE
Feature suggestion (azimuthal scroll) 

### ISSUE THREAD

**Issue by akrygier** [HEXRD/hexrdgui#1059]
It would be nice to have a feature where you could add a constant value to the azimuthal, effectively allowing you to scan (this is more true for PXRDIP than TARDIS).

In the image below, I would like to be able to effectively translate the cake up so that the region of maximum 2 theta is at eta = 0.

![image](https://user-images.githubusercontent.com/59886900/137364755-a6ecbd9a-430c-4354-a31a-e90ee6132a12.png)

**Comment by psavery** [comment]
Hi @akrygier,

This can (kind of) be done, at least visually, by editing the eta range in the "Image Mode" widget for the polar view. Rather than a range of -180° to 180°, for instance, it could be changed to -90° to 270°.

Now, this wouldn't put the maximum two theta at eta == 0, but it would shift the eta axes so that the maximum two theta appears in the middle vertically.

**Comment by joelvbernier** [comment]
what @psavery said :-)
