### ISSUE TITLE
Setting active reflections (rings) in materials pane

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#107]
we would like to be able to have the user select the active rings they want from the displayed list by two methods:

1. Using the mouse (ctrl and shft click)
2. By specifying a maximum bragg angle
3. By specifying a minimum d-spacing

The PlaneData class has an "exclusions" attr that is a boolean mask to select a subset of the complete list of generated reflections (as specified currently by the max sum of h^2 + k^2 + l^2).  There is also a tThMax attr that is initialized as None, but if set to a float, it treats it as a cutoff on 2theta.  I can code up a dspMin attr to handle the 3rd case.  Setting PlaneData.exclusions = None resets to display all.

This functionality was in the old wx GUI under the "edit HKLs" button.

**Comment by psavery** [comment]
As of #236, the materials now default to selecting the first 5 rings when they are modified. When a material is added, it has the same exclusions as the previously selected material (from which it was copied).

With regard to my comment above, #236 now also makes it so that the rings that are selected in the materials panel are the ones that are used during calibration.
