### ISSUE TITLE
Fixes to existing calibration methods

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#1107]
Hey @psavery -- I noticed that a few things were 'off' in the calibration, so I started a fix branch under PR #1106.

Testing so far looks good, but there are still a few things that need to be addressed:

- [x] The lattice parameter(s) are not getting updated on the material in the "fast powder" method even if they are flagged for refinement; it echos back the changed values, but that must be on a copy of the material's `PlaneData`, and so there is no update of lattice parameters once the optimization is finished.
- [x] The mixed Laue/Powder calibration is still buggy.  Seems to behave badly if points are deleted (could not reproduce - may be fixed by refactoring, such as in #1223. Re-open if still an issue)
- [x] We need to be able to store the picks so that subsequent calibrations can be re-run without haveing to re-pick (fixed by #1223)

**Comment by joelvbernier** [comment]
@psavery -- let's try to connect on this before next week's meeting.

**Comment by psavery** [comment]
@joelvbernier Sounds good

**Comment by psavery** [comment]
> * [ ]  The mixed Laue/Powder calibration is still buggy.  Seems to behave badly if points are deleted.

So, I actually just ran through the simulated tardis example (it has one powder and one laue overlay), and I compared
the difference (in the picks data, which is input to the calibration methods) between skipping points (not picking at all) 
and picking then deleting. It looks like they are the same, so it looks to me that the deleting behavior is working as
intended (if you delete a point, it is as if you skipped it).

However, maybe you are doing something different from what I did. If you can reproduce the issue, maybe you can
change [this line](https://github.com/HEXRD/hexrdgui/blob/ace51145e34f15809d0c27e4de3f3142d0dd7f21/hexrd/ui/calibration/calibration_runner.py#L342) to be `self.dump_results()`, and then run it again? If you do that, it will dump basically all of the
input to the calibration methods, and we can take a closer look to see if the input to the calibration methods is correct.
This will help us determine whether the problem is in the input to the calibration methods, or in the calibration methods
themselves.

> * [ ]  We need to be able to store the picks so that subsequent calibrations can be re-run without haveing to re-pick.

You mean storing them internally, right?

We can actually already do via files. Basically, when you run through the calibration, you can at any point click 
"Picks Table" to view the picks table, and then you can save/load your picks. But storing them internally would
be faster.
