### ISSUE TITLE
Add ability to set detector panel buffer from masks.

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#1226]
We could use a 3rd option for configuring the panel buffer on the detector: set from masks.  I have lost track of the logic of how the various masking options are handled @bnmajor -- but we could make it explicit regarding setting the `panel_buffer` attribute on each detector with the masks defined on that detector.

**Comment by psavery** [comment]
> Also add the ability to remove the panel buffer.

I'm gonna make this one a separate issue

**Comment by psavery** [comment]
@bnmajor Perhaps the threshold masks are set up differently internally than the other masks, and because of that, setting the panel buffer from masks misses it?

**Comment by bnmajor** [comment]
@psavery Yes, I'm almost positive you're correct.
@joelvbernier I can get the fix in for the threshold masks as well as add the additional options tomorrow.

**Comment by joelvbernier** [comment]
Seems like "greater than" behaves like one would expect, but both equal to and less than have no effect.  If those are actually getting set to an array of all `False` then I can't say setting the panel buffer isn't working...  since currently that option seems to clab her the panel buffer, which would check out.

**Comment by bnmajor** [comment]
@joelvbernier How should we be handling threshold masks in the case of setting the panel buffer from the applied masks? Right now they are held separately from the raw masks because they are generated on a per-image and per-frame basis. For all other masks (hand drawn, panel buffer, etc) they are simply 2-D masks that are applied to the image. If the image is aggregated or a single frame it is no problem to update the panel buffer, but if it is an un-aggregated imageseries how would the panel buffer be updated? As a 3-D array with a mask for each frame?

**Comment by psavery** [comment]
Maybe either that, or aggregate the threshold masks into one 2D image?

**Comment by psavery** [comment]
@joelvbernier says to just use whatever is displayed.

**Comment by joelvbernier** [comment]
Yes, admitedly the use case of an unaggreagted image series is ill-defined, so the only sane choice is to use whatever is displayed.
