### ISSUE TITLE
Powder overlay issue

### ISSUE THREAD

**Issue by saransh13** [HEXRD/hexrdgui#1235]
Powder overlay not showing up on one of the TARDIS panels.

![Screen Shot 2022-05-31 at 12 33 53 PM](https://user-images.githubusercontent.com/15834451/171270325-ec7ff32b-5979-4e11-a06b-bde82388c84e.png)

**Comment by psavery** [comment]
@saransh13 So I think you must have run into a situation where the eta period in the overlay are not being synchronized with the eta period in the hexrdgui settings. Do you know the exact steps you took to cause this?

Then again, it might be worth considering for us to refactor this in a way so that the overlay always uses the eta period in the hexrdgui settings, so that there will be no synchronization issue.

**Comment by psavery** [comment]
@saransh13 Even though I was unable to reproduce your issue, I believe #1236 should fix it. Could you confirm with me that fixes the issue for you?

**Comment by saransh13** [comment]
Yes, it does fix the issue! PR LGTM
