### ISSUE TITLE
TARDIS image plate outline disappears when rotating

### ISSUE THREAD

**Issue by akrygier** [HEXRD/hexrdgui#1300]
When I am loading TARDIS image plates and I try to rotate the image, the cyan outline disappears as soon I try to move it. This happens both with the keyboard up/down keys and dragging with the mouse.

**Comment by joelvbernier** [comment]
Yep, found it.  Something *REALLY* strange going on.  If you apply the transform _on load_ instead of via the "Add Transform" button, everything is fine.  If you use the transform button on the importer, the mouse rotate causes the outline to disappear, but the arrow keys work fine.  I'll make a note and try to figure out what is happening; the weird thing is that the mouse and the key inputs follow the same code path!

**Comment by joelvbernier** [comment]
Any Matplotlib interactive canvas wonks, we could use help here!

**Comment by akrygier** [comment]
This does not seem to be an issue anymore and could probably be closed.

**Comment by psavery** [comment]
Thanks @akrygier!
