### ISSUE TITLE
excessive memory usage when using man processes

### ISSUE THREAD

**Issue by donald-e-boyce** [HEXRD/hexrdgui#1329]
Memory usage can get out of hand when using many processes. I am guessing this is because the same images are loaded on each process. Maybe we can arrange for the processes to load images to shared memory.

Another possibility would be to have one process load the images and then send data and tasks to the other processes. For example, in fitting grains, there could one process that finds the spots on the images. Then for each spot, it constructs a smaller 3D numpy array for that spot and tasks another process with the fitting for that spot.

**Comment by psavery** [comment]
That all sounds good, Don.

If we could get a specific example of this we could try out, that would be particularly helpful (as I'd be able to analyze it more thoroughly to see what is going on).

One thing I can note: for some of the functions that use multiprocessing, the whole image series objects are pickled and sent between the processes. As for how much memory will be used, the type of image series makes a difference. For the HDF5 image series, I believe no data is copied, since those image series just hold a handle to the file. But for the frame cache image series (i.e., NPZ files), I believe the sparse data is copied.

We may be able to design the multiprocessing functions differently, like you mentioned, where we don't send the whole image series objects over. But having an example would be very helpful to determine this :-).

**Comment by psavery** [comment]
For the monolithic ruby example (state file [here](https://github.com/HEXRD/examples/blob/master/NIST_ruby/multiruby_dexelas/include/dexelas_id3a_20200130.h5)), it appears that when `fit-grains` is ran, each process takes up about 10 GB of memory. I can actually only run it if I start `hexrdgui` with the `-n 1` argument (I have 31 GB of RAM), since it has 3 grains and by default runs 3 processes.

For that example, `fit-grains` is the only step that has a big memory issue. Maybe we should look into `fit-grains` and see why it is using up so much memory?

**Comment by psavery** [comment]
To be fair, it looks like the `hexrd` command line is also using up about the same amount of memory as well when it is running `fit-grains` for the same example, so this may be something we need to fix in `hexrd`.

**Comment by psavery** [comment]
One option is that we can look into using the array image series for a single spot so we can more easily zoom into that section.

**Comment by psavery** [comment]
To follow up on this, we isolated the memory issue to be the returned object [here](https://github.com/HEXRD/hexrd/blob/cd08e3f1ea6ec02eecf16af002aba35666a90882/hexrd/instrument.py#L1848-L1854).

This object is **very** large. For the monolithic ruby example, it is about 4 GB per detector.

@donald-e-boyce Is working on making that method into a generator method, so we can just iterate over the output rather than create a single giant output object. He has seen the memory usage decrease significantly, and will put up a PR soon.

**Comment by psavery** [comment]
This issue may be fixed by hexrd/hexrd#511.

**Comment by psavery** [comment]
Fixed by https://github.com/HEXRD/hexrd/pull/511
