### ISSUE TITLE
Polar and stereographic powder overlays for cylindrical detector

### ISSUE THREAD

**Issue by saransh13** [HEXRD/hexrdgui#1362]
The powder overlays for the cylindrical detector seems to connect the wrong powder lines together. Some screenshots attached below. Need to be fixed before the cylindrical detector is merged into master.

<img width="610" alt="Screen Shot 2023-03-27 at 9 58 58 AM" src="https://user-images.githubusercontent.com/15834451/228013132-d01ae47d-b350-4834-9b61-ffe9e9afd9fe.png">

<img width="602" alt="Screen Shot 2023-03-27 at 9 58 42 AM" src="https://user-images.githubusercontent.com/15834451/228013148-9a3ba0c7-58b1-4224-8036-a163ba68dab9.png">

**Comment by psavery** [comment]
We can probably modify the lines around [here](https://github.com/HEXRD/hexrdgui/blob/089bf62758d2571ea0eae3d0ece95de46de20357/hexrd/ui/overlays/powder_overlay.py#L371-L377) to fix that. Currently, that code is just checking to see how far apart the point at the min eta and the point at the max eta are, and if they are a certain distance apart, it makes sure they aren't connect (this is important if the panel is, for example, split so that half is on the top and half is on the bottom of the polar view).

We may need to check the angular distance between all points now because of cases like this, where the points on the cylindrical detector that are being connected are far away from each other. And if the angular distance is greater than a certain amount, insert a nans row to disconnect them in the drawing.

**Comment by psavery** [comment]
Maybe we should just do this extra check for cylindrical detectors only since it might only be specific for them.

**Comment by psavery** [comment]
This was fixed in [this commit](https://github.com/HEXRD/hexrdgui/commit/8116df8d079a2fdde1b7d259803bc7ceb0aafe4a).
