### ISSUE TITLE
Mask range issue

### ISSUE THREAD

**Issue by akrygier** [HEXRD/hexrdgui#1369]
If I make a mask and then change the 2theta or eta range such that it intersects the mask, the mask will sometimes extend across the entire displayed azimuthal range.

**Comment by saransh13** [comment]
@akrygier can you post a screenshot with this issue?

**Comment by akrygier** [comment]
Masked polar image with azimuthal range -90:270
![image](https://github.com/HEXRD/hexrdgui/assets/59886900/274eec75-3ce2-4db0-993a-aefba11adb62)

Same image with azimuthal range changed to -270:90
![image](https://github.com/HEXRD/hexrdgui/assets/59886900/a24ea6a3-528e-4a24-a8ba-fb44f1966b85)

This happens when you simply narrow the range sometimes too, which is the real failure mode since users plausibly do that from time to time. (ie, -270:90 is not a typical azimuthal range, but it does demonstrate the issue)

**Comment by psavery** [comment]
Yeah, we need to fix this

**Comment by psavery** [comment]
I have a fix for this in #1486. Basically, we did the following:

1. Add a check to see if the mask in the polar view is being split on top and bottom (this is being done by checking if two consecutive points on the line around the mask have an eta difference greater than 180 degrees, which should never happen).
2. If it is split, then break it up into two separate polygons on the top and the bottom.
3. Add a couple of extra points to the polygons so that they extend to the edge of the eta border. We interpolate in two theta so that these points are going in the right direction.

**Comment by akrygier** [comment]
👍 🙏
- Andy
