### ISSUE TITLE
Masking tool hidden by main window

### ISSUE THREAD

**Issue by akrygier** [HEXRD/hexrdgui#1371]
When you want to add a mask element, the window that pops up is hidden by the main window. It would save time if that was not the case (ie, have the mask tool window open up to the left of the main window). I usually end up chasing the main window across the screen and in a few clicks have to start over again. Is it possible to have the mask work more like Dioptas where there's a separate tab with dedicated controls in the gui?

**Comment by psavery** [comment]
Which dialog is this? The one for `Apply Hand Drawn Mask`?

We might need to set the `Qt.Tool` flag on one of the dialogs so that it stays on top. Unfortunately, we don't always notice this issue since I believe it is OS-specific.

@bnmajor Can you make sure each of the mask pop-ups has the `Qt.Tool` flag so it stays on top?

We could also put it in a separate tab, but it would require a little re-design. We could potentially put it in a dock widget. But setting the `Qt.Tool` flag might be the easiest solution for now. If we come up with a good re-design plan, we can go with that too!
