### ISSUE TITLE
gui not plotting material lines with overlay manager

### ISSUE THREAD

**Issue by wehrenberg1** [HEXRD/hexrdgui#1388]
I can't get material XRD lines to plot over my images.  My proceedure is to load the material in the Materials window.  Go into Overlay Manager.  Click Add.  Then make sure the material has the "Visible" box checked.  No lines are plotted.  I'm not getting any error messages.

**Comment by wehrenberg1** [comment]
Ah nm, need to click Show Overlays.  Maybe this could be the default?

**Comment by psavery** [comment]
> Ah nm, need to click Show Overlays. Maybe this could be the default?

If I start the program via command line like `hexrdgui --ignore-settings` (which ignores previous GUI settings), it looks like the `Show Overlays` box is checked, which means it is checked by default.

Maybe you unchecked it in a previous session, and then exited the program normally (via the "x" button)? When that happens, it saves your GUI settings so that the next time you start up, it has the same settings.
