### ISSUE TITLE
Masks not working as expected

### ISSUE THREAD

**Issue by saransh13** [HEXRD/hexrdgui#1458]
Once masks are applied to the cylindrical detector and view is switched, or if state file is saved, then the masks vanish.

**Comment by psavery** [comment]
@bnmajor After a polar mask is drawn, because we save the points in raw coords for future use, we should also immediately perform the conversion from raw to polar and use those coordinates for the mask. That prevents the inconsistency where if we switch views and come back the masks appear different (or don't appear at all if there is an issue in the conversion).

**Comment by psavery** [comment]
Upon further examination, it looks like masking on the cylindrical detector **is** working properly. But if you draw a mask that spans multiple detectors (or part of the mask is in a `nan` region), that produces the issue. After discussion with @saransh13, we should add the ability to draw masks over multiple detectors, and allow drawn masks to extend out into nan regions - although they will be modified internally so that they do not extend into the nan regions. I will look into these.
