### ISSUE TITLE
What is the implication of choosing "current" or "load" configuration

### ISSUE THREAD

**Issue by akrygier** [HEXRD/hexrdgui#1463]

**Comment by bnmajor** [comment]
@akrygier The config file is what is the instrument file that will be used when all detectors have been cropped and the `Complete and Reload` selection has been made. The quick summary is:

> - Current Configuration: This will used the current instrument config
> - Load Configuration: If selected, you may then either use the default configuration file that we provide or load your own. Uncheck the Default box to load your own configuration.
> 
> If you are unsure what to use, try the default config.

This is designed to allow you to use an existing config(instrument) file that you know is set correctly if it is already loaded (`Current Configuration`) or if you would like to load it yourself (`Load Configuration`, `Default` unchecked). You can see the default [TARDIS](https://github.com/HEXRD/hexrd/blob/master/hexrd/resources/tardis_reference_config.yml) and [PXRDIP](https://github.com/HEXRD/hexrd/blob/master/hexrd/resources/pxrdip_reference_config.yml) config files that are used if that is the option you choose. The [docs](https://hexrdgui.readthedocs.io/en/latest/configuration/images/#llnl-import-tool) have been updated recently to cover a lot of this as well!

**Comment by akrygier** [comment]
So current configuration is essentially allowing you to skip the import part (where you select image regions, etc.)?

**Comment by bnmajor** [comment]
No, you will still go through all of those steps if you choose to load your data through the LLNL Import Tool. When you use that tool though it needs an updated instrument file at the end in order to load all of the detectors and their associated data. If you choose the `Default` option it will use the files referenced above (skipping any detectors that were not completed), or you can use a file that you currently have loaded (maybe from the last import) or that you have saved somewhere (maybe saved from a previous import or shared with you from someone else). In all three cases the cropping and rotation of the outline will update the tilt and pixels rows and columns in the instrument file.

If you want to load images that have already been cropped with an instrument file of your choice you can use the [config load](https://hexrdgui.readthedocs.io/en/latest/configuration/instrument/#loading-and-saving) and [image quick load](https://hexrdgui.readthedocs.io/en/latest/configuration/images/#quick-load) options.

**Comment by bnmajor** [comment]
> right under the Instrument, we could have a Configuration: label with a combo box that has the options Default (to use the default configuration), Current to use the current one, and Load from File to load from a file

This update suggested by @psavery has been added to #1483 to make the UI a little simpler

**Comment by psavery** [comment]
We reworked this so that hopefully it is a little less confusing. I'm going to close this. Feel free to reopen if needed.
