### ISSUE TITLE
All menus/objects disabled after powder/laue calibration

### ISSUE THREAD

**Issue by akrygier** [HEXRD/hexrdgui#1556]
This has happened a couple of times; not sure what triggers it.

When I calibrate image plates, some times all of the menus, etc. are disabled. When this happens there is nothing I can do except kill hexrdgui and restart.

<img width="1791" alt="image" src="https://github.com/HEXRD/hexrdgui/assets/59886900/18b3a641-708b-4636-ba7e-b2b0f45d10ae">

**Comment by psavery** [comment]
@akrygier I was worried this might happen! We disable all of the menus during point-picking because if the user changes something in the menus during point picking, it might break the program.

However, a very bad situation is accidentally leaving all menus disabled after point-picking, because you can no longer interact with the GUI!

I think I have fixed this in #1557. After we merge it, can you let me know if you run into this issue again? If so, we can try to look into more thorough protections to keep it from happening.

**Comment by psavery** [comment]
Awesome!

**Comment by akrygier** [comment]
This is happening again

**Comment by psavery** [comment]
For the Powder/Laue calibration, right? I might need to just get rid of the disabling entirely.

**Comment by akrygier** [comment]
Yes, for powder/laue.

I think you are probably right. The calibration does not take so long that I have ever felt tempted to start pushing new buttons, etc.
