### ISSUE TITLE
Dock overlay manager

### ISSUE THREAD

**Issue by saransh13** [HEXRD/hexrdgui#1564]
Thoughts about docking the overlay manager in the main window? This was a request from one of the users.

**Comment by psavery** [comment]
I think this sounds good.

@bnmajor Do you know how much work this would be?

**Comment by bnmajor** [comment]
@psavery Not too long but I think it'll take more than a few minutes because if I remember correctly there are some quirks to getting dockable widgets to play nicely when they're launched after app startup. Tops two hours if there are issues like I remember having with the LLNL import dialog? Much less than that if not.

**Comment by psavery** [comment]
Sounds good, go ahead!
