### ISSUE TITLE
Image borders for cartesian and polar views

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#163]
Need to export detector boundary separately for these views with a toggle for display.  Requires additional output from rendering code.

**Comment by cryos** [comment]
This is working, I want @joelvbernier to verify it works as he wants before closing the issue out.

**Comment by psavery** [comment]
Yeah, so I think this is indeed working. However, it currently works by editing the image, rather than drawing an extra plot on top of the image (as is done for the overlays). This makes it so that the azimuthal integration in the polar plot is affected by the borders. I'm wondering if we should get it to start drawing an extra plot on top of the image instead of modifying the image.

**Comment by cryos** [comment]
Yes, that is what must happen at this point as we start to rely on that plot more. Let's prioritize this
