### ISSUE TITLE
Masking issue

### ISSUE THREAD

**Issue by saransh13** [HEXRD/hexrdgui#1651]
The point selector for `polygon` mask is still on while I'm in the `ellipse/rectangular` masking option.
Applied ellipse/rectangular masks
Applied polygon masks
The went back to apply ellipse/rectangular masks.

Screenshot of the test case
<img width="1387" alt="Screenshot 2024-01-12 at 12 33 50 PM" src="https://github.com/HEXRD/hexrdgui/assets/15834451/3b9d2a84-b815-4cc9-aeb5-28ada4332575">

**Comment by bnmajor** [comment]
Thanks @saransh13! I had actually experienced this before but have been able to reproduce in order to debug and fix... I tried your steps and I'm not seeing the bug. I'll try to look into this some more but if there any other steps or details you can share (even if they seem unrelated) that would be helpful!

**Comment by psavery** [comment]
I think I was able to reproduce a closely related version of this. Here is a video, along with the steps:

1. Load [this state file](https://github.com/HEXRD/examples/blob/master/state_examples/DCS_fast_powder/dcs_fast_powder_refine_beam_energy.h5)
2. Hide the overlays
3. Create a polygon mask in the raw view
4. Switch to the polar view. The cursor is still there.

https://github.com/HEXRD/hexrdgui/assets/9558430/d46ce27b-06b9-488c-a1e4-54d67545165b

**Comment by psavery** [comment]
Kazam is not catching my mouse pointer :slightly_frowning_face:

**Comment by bnmajor** [comment]
Thank you @psavery!!
