### ISSUE TITLE
polar view recalculation triggered after save state

### ISSUE THREAD

**Issue by saransh13** [HEXRD/hexrdgui#1694]
After saving state file, the polar view seems to be calculated again. Can we switch this trigger off?

**Comment by psavery** [comment]
To add further detail, I think this only happens when you save over a currently opened state file. I think this is happening because we have to re-create the imageseries so that they point to the new state file (the imageseries can no longer refer to the old file since it was overwritten, and new imageseries have to be made). We might still be able to avoid the recalculation, though.
