### ISSUE TITLE
Material inputs are slow...

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#312]
In v0.7.1, I've noticed that the inputs (e.g., changing a material's name, making a new material) are prohibitively slow.  Is it regenerating the entire material with every keystroke/input?  Maybe we need to force enter or tab in the name field at the very least to improve usability -- we have to do something because it is not very usable in it's current state.

**Comment by psavery** [comment]
I think that only a shallow copy should be made. That is done [here](https://github.com/HEXRD/hexrdgui/blob/50c7528128ea8057150f6d2a62d4f730eb3c343b/hexrd/ui/hexrd_config.py#L754-L755).

The [gui is also updated](https://github.com/HEXRD/hexrdgui/blob/50c7528128ea8057150f6d2a62d4f730eb3c343b/hexrd/ui/materials_panel.py#L324), which might cause a little slowness.

However, updating the internal config and GUI with every keystroke was definitely a problem. That should be fixed in #313, where the update is only performed after the user finishes typing. This should hopefully fix the problem for the most part.
