### ISSUE TITLE
distortion overhaul

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#420]
I'll put you on notice that I am finally fixing the distortion, which remains to be `None` or hard coded the the 6-parameter GE-style function that is defined in distortion.py

Summary of the changes:

1. distortion.py is moving to a package
2. defining an abc to provide a single interface for the distortion application
3. start a registry of different adapters for the various distortion functions (which have different length parameter lists)

Questions:

- do we want to always have a distortion class generated and just have a null case rather than using `None`?
- different distortion functions will have different length parameter lists; I recognize this creates issues for the GUI -- do we need to generate a separate widget for handing the distortion?  Tree view might not care, but the forms view will...

This is related to  #418 
I'm working this now...

**Comment by psavery** [comment]
About the GUI, there might be a better way to do this (that involves dynamically creating spin boxes), but I think these steps will work as well for the new distortion cases:

1. Determine the max number of parameters that any of the distortion functions may have.
2. Add spinboxes for the max number of parameters in [the UI file](https://github.com/HEXRD/hexrdgui/blob/master/hexrd/ui/resources/ui/calibration_config_widget.ui). It currently has 6.

![Screenshot from 2020-07-17 13-36-56](https://user-images.githubusercontent.com/9558430/87815168-2651be00-c833-11ea-83e3-f44a2cc790a0.png)

3. Add the new spin box names to [this parameter list](https://github.com/HEXRD/hexrdgui/blob/ff2f6cb716318634d46716ff5283552249bbdde3/hexrd/ui/resources/calibration/yaml_to_gui.yml#L12-L17).

4. Add the new distortion cases [here](https://github.com/HEXRD/hexrdgui/blob/ff2f6cb716318634d46716ff5283552249bbdde3/hexrd/ui/hexrd_config.py#L1297-L1304).

If everything works correctly, this **should** automatically hide parameters so that the number of parameters in the form view is equal to the number of parameters of the distortion function.

**Comment by cjh1** [comment]
@joelvbernier Are the changes in hexrd for this done?

**Comment by cjh1** [comment]
@joelvbernier I think this can closed now?

**Comment by psavery** [comment]
I don't think this needs any updates until more distortions are added. As more distortions are added, we will need to add the options to use them to hexrdgui as well (along with the number of parameters for each).

**Comment by cjh1** [comment]
Closing for now
