### ISSUE TITLE
fit grains: Add matplotlib toolbar ( so we can save plot )

### ISSUE THREAD

**Issue by cjh1** [HEXRD/hexrdgui#460]

**Comment by psavery** [comment]
We currently have [a custom navigation toolbar class](https://github.com/HEXRD/hexrdgui/blob/f1d049096c16ec0298ba66053d239ba25a39558c/hexrd/ui/navigation_toolbar.py#L4) that  inherits from the matplotlib one but turns off the subplots button, since that is available elsewhere in the GUI.

We can either use that, or if we want to keep the subplots button for this, we can just use the navigation toolbar here:
```
from matplotlib.backends.backend_qt5agg import NavigationToolbar2QT
```

If it works for the 3D plot the same way it does for the 2D plot, then we only need to construct it with the canvas as the first argument (like [here](https://github.com/HEXRD/hexrdgui/blob/f1d049096c16ec0298ba66053d239ba25a39558c/hexrd/ui/image_tab_widget.py#L142)), and then add it to a QLayout for display.

**Comment by psavery** [comment]
Before the latest matplotlib (3.3.2), only the save button in the navigation bar worked. So that is currently the only one displayed.

However, it looks like for 3.3.2, now the [home, back, and forward buttons work](https://matplotlib.org/3.3.2/users/whats_new.html#home-forward-backward-buttons-now-work-with-3d-axes). Should I add those in?

**Comment by cjh1** [comment]
@psavery Yes, lets add the ones that work.

**Comment by psavery** [comment]
So, I've tried them out with the latest matplotlib. The home/back/forward buttons work better now, but are still buggy. For instance,  the forward button is often enabled when it shouldn't be, and the home button sometimes thinks a different configuration is home that is not. I can put them in with the hope they will be less buggy in the future.

We have a ranges editor now as well (#648). I'll need to make sure the ranges get updated when the buttons get pressed, because home/back/forward do affect ranges.

Zoom/pan still don't do anything, so I'll leave them out.
