### ISSUE TITLE
creating new material using the structures tab

### ISSUE THREAD

**Issue by saransh13** [HEXRD/hexrdgui#545]
I just got around to testing a new material creation feature. There are a few improvements to be made. I'm listing them here.

1. When a new material is created and the user switches to the structure tab and clicks on any site, then the arrow to add/import/delete material gets hidden. 

2. All the data for the new material is reloaded from the previous material that was selected. The new material should have empty data fields. Once the first site is added using the "+" button, then the form below should appear. 

3. `site Atoms Types` should initially be empty. It should also have a remove button just like the site.Once an atom is selected, the default values of `occupancy = 1`, `Fractional coords = (0,0,0)` `Thermal factor type = U` and `U = 1e-6` can be used. Currently, these values default to values for the last selected material.

4. It should be possible to remove all sites using the remove button. Right now the remove button (the "-" button) is disabled once there is only 1 site left.

5. The name of the site are currently not editable. This should be editable by the user.

6. An occupancy of less than 1 for a site should be allowed. Only occupancy greater than 1 should be highlighted in red.

**Comment by psavery** [comment]
Hi Saransh. Here are my responses for further thought.

1. I haven't been able to reproduce this on Linux. I'll give it a try on Mac later.

2. The current behavior in the general tab is that when a new material is added, its properties are copied from the most recently selected one. For the structure tab, we can make it so that the sites are not copied. And, indeed, if no atom site is selected, then there is no form displayed below it. If we change the behavior so that the new material does not start with a site, then there shouldn't be a form below it until the user adds a site.

3. There is currently a requirement in the GUI that all sites must have at least one atom type. I can remove this requirement so that the atom types can be empty. The current way the user removes atoms is by opening the periodic table and de-selecting the atoms they want removed, but I can add a minus button that the user can click as well. The atom data defaulting to the values of the last selected site/material was intentional, but I can get them to default to the values mentioned above instead.

4. Okay. I did not think a material without a site was possible. But I can change it so the user can remove the last site.

5. The names of the sites are actually editable. You just need to double-click them. Note that I don't think the site names are stored in hexrd currently, so if you write out a material and load it back in, it will have automatically generated site names that might not be the same.

6. The red boxes indicate that the sum of the occupancies don't add up to the total occupancy. You can hover your mouse over the red boxes to see a tooltip with this message. There is currently no min/max restriction on the occupancies. But I can make the total occupancy have a max of 1.

All of that said, I am wondering if we should keep the "Total Occupancy" the way that it is. The "Total Occupancy" is currently set by the user, and if the user modifies any of the atom occupancies, then they have to modify the "Total Occupancy" as well so that it is equal to the sum of the atom occupancies. We could potentially instead make it so the "Total Occupancy" is not editable by the user, but automatically generated by summing the atom occupancies. What do you think?

Also note that we have not yet implemented a way to specify "U" as a tensor. If you select/load a material that has "U" as a tensor, there will be errors in the terminal, and the GUI behavior may not be as predictable. This is being tracked in #513.

**Comment by saransh13** [comment]
Thanks, Patrick. Attaching gif for the first issue here.

![vanish](https://user-images.githubusercontent.com/15834451/93912727-fb636a80-fcb8-11ea-97b8-b716f74610b8.gif)

2. see 4.

3. Yes, there should be at least one atom type for each site. I couldn't figure out how to remove an atom that had already been selected. A "-" button makes more sense to me than deselecting from periodic table. I think we definitely want to start with an empty form here.

4. You're correct. Material without a site doesn't make any sense. I think I wanted to remove all sites because the names were not editable on Mac. If thats fixed, then having one site by default is okay.

5. I can't edit the names on a Mac. The double click doesn't seem to work. 

6. The max occupancy should definitely be enforced.

Yes, your idea makes sense. Total occupancy can just be a sum of the individual atom occupancies.

**Comment by psavery** [comment]
@saransh13 It looks like we are going to be putting off the mac fixes for now, unfortunately. I want to get to them, but we don't think we'll have time before the demo. I'm going to try to fix the other things, though.

For 5, can you try selecting the row and then typing? That seems to work for me. In Qt, there's a concept called "Edit Triggers" for the table view, and you can see which ones I have selected here:

![Screenshot from 2020-09-25 10-02-33](https://user-images.githubusercontent.com/9558430/94276482-5219b000-ff16-11ea-8ab2-2a75bf1074ee.png)

"DoubleClicked" is selected, so it should work, but I'm not sure why it doesn't work on the Mac.

"AnyKeyPressed" is also selected, which in theory means that if the row is selected, and you start typing, it should start editing the name immediately.

**Comment by psavery** [comment]
General issues to do:
- [ ] Add minus button to remove atom types
- [ ] Set a max total occupancy of 1
- [ ] Make the total occupancy calculated and un-editable, rather than something that gets set by the user
- [ ] Make a default site that gets created for new materials (don't copy the site from the previously selected material)

Mac issues to do:
- [ ] The add/import/delete material tool button disappears when adding a new material and then selecting a site
- [ ] Site names are not editable on Mac (on Linux, double-click or select and start typing both seem to work)

**Comment by psavery** [comment]
@saransh13 I think the site names should now be editable because of #603. Can you give it a try on Mac and see if it works?

**Comment by saransh13** [comment]
Still not editable on Mac for me.

**Comment by joelvbernier** [comment]
Or windows.

**Comment by psavery** [comment]
We are going to remove the site editor entirely in #779, and so there won't be a need to edit site names.

If the add/import/delete material tool button is still disappearing on Mac, we should maybe open up a new issue for that.
