### ISSUE TITLE
WPPF behavior with spline interpolation as background method

### ISSUE THREAD

**Issue by saransh13** [HEXRD/hexrdgui#600]
When spline was chosen as the background from the previous session, clicking on the `WPPF` option in thr `Run` menu directly opens up the `matplotlib` window to pick points. One that is done, then the form appears. GIF below

![out](https://user-images.githubusercontent.com/15834451/94491620-69b69a00-019d-11eb-9c18-b4c0c32da3e0.gif)

**Comment by psavery** [comment]
I think I know how to fix this. Should be easy.

**Comment by saransh13** [comment]
@psavery Theres also a minor issue with the updating of the lattice parameters. The `a` and `c` on the materials panel don't match the corresponding values in `WPPF` form. Attaching image.

![Screen Shot 2020-09-28 at 3 24 10 PM](https://user-images.githubusercontent.com/15834451/94492310-e433e980-019e-11eb-8dd8-eba5f4360175.png)

**Comment by psavery** [comment]
@saransh13 So, I think this saves the previous settings that were output from WPPF and then just displays those settings again the table. If there were no previous settings, then it uses the value from the material.

But we probably want it to always use the value for the material as the starting value, right?

**Comment by saransh13** [comment]
I think the way you have it set up right now is okay. We just need to make sure that the values in `Material` after executing `WPPF` is the same as this form. In the image above value of `a` and `c` are exactly the same, which makes me suspicious that they were not set correctly.

**Comment by psavery** [comment]
I think if you run WPPF and then after it finishes, open the WPPF options dialog back up, I think the numbers should match exactly. But if, after running WPPF, you modify the material lattice parameters and then open the WPPF dialog back up, it will probably have the output from the first WPPF run set rather than the modified material lattice parameters. So they will be different.

Additionally, if you exit hexrdgui normally, the settings get saved, so that if you start the program back up, and then you have a material with the same name as before with powder overlays, then open up the WPPF dialog, it will also have the output of the last run of WPPF set to the materials again rather than what the material lattice parameters are.

If you experience a mismatch in the numbers in a different way than from the two scenarios mentioned above, can you record the steps so I can repeat it?

I personally think it is more intuitive for the material lattice parameters in the WPPF options dialog to always be set to whatever the material has on it rather than the last WPPF run (which may or may not be the same). So I am happy to change it to that if you think it's more intuitive as well.

**Comment by saransh13** [comment]
Oh okay, got it now. Yeah that sounds better.
