### ISSUE TITLE
Material reflection table is getting clipped by instrument beam energy

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#609]
I noticed that the reflection table for a material is getting clipped by the beam energy specification on the instrument.  I suspect this is because reflections up to a certain dmin specification can have a 2&theta; value of NaN from the arcsin in Bragg's Law (&lambda;/2d >1), which is fine...  the problem with this behavior is that it artificially clips the reflection list needed for the Laue overlays; the Laue simulations are not tied to the instrument wavelength, but rather a range of energies.

So -- we need to remove this clipping (which is not happening in the material according to @saransh13) and simply prevent those reflections with 2&theta;=NaN from being used to draw powder overlays.

**Comment by joelvbernier** [comment]
Update -- loaded a saved h5 material file and it seems like it doesn't get clipped?

**Comment by psavery** [comment]
So, the number of entries in the materials table is determined solely by the output of [`PlaneData.getHKLs()`](https://github.com/HEXRD/hexrd/blob/68aaecadebbede868b774bed9218ded3c63053bb/hexrd/crystallography.py#L1084) with the exclusions of the plane data all set to `False`. We don't tie the materials table directly to the Laue spots, but the Laue spots are [also generated from a `PlaneData` with all exclusions set to `False`](https://github.com/HEXRD/hexrdgui/blob/40abd5f8cd6ebef9340e3eee9e66697b46aee6d2/hexrd/ui/overlays/laue_diffraction.py#L49-L55), so they might appear similar to the results from the materials table.

However, the max 2θ in the materials panel is set on `PlaneData.tThMax`, which limits the output of `PlaneData.getHKLs()`. This affects both the number of entries in the materials table and the number of laue spots that get generated in hexrd. See attached gif below.

![laue_limit_active](https://user-images.githubusercontent.com/9558430/94804008-25ebac80-03b8-11eb-89a6-f7d1d6e5486c.gif)

Because changing the beam energy also changes the 2θ of the reflections, I suspect that, if there is a max 2θ in place, changing the beam energy will also change the number of reflections that are displayed (the ones that have a 2θ less than the max 2θ). And this is probably what is causing the change in the number of reflections with the change in the beam energy.

Also, loading a saved h5 material file probably changes the max 2θ, and this would change which reflections are displayed as well.

**Comment by psavery** [comment]
Note that it looks like where there are NaNs, they still show up in the materials table

![Screenshot from 2020-10-01 07-55-00](https://user-images.githubusercontent.com/9558430/94806124-7adcf200-03bb-11eb-9b9e-377b3cf4dd06.png)

**Comment by joelvbernier** [comment]
Not sure how to reproduce this.  I'll reopen if I encounter it again.
