### ISSUE TITLE
TypeError on mouse hover over raw image canvas

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#641]
Notice this being spit to stdout
```
File "c:\users\berni\onedrive\documents\github\hexrdgui\hexrd\ui\main_window.py", line 832, in new_mouse_position
    labels.append('value = {:8.3f}'.format(info['intensity']))
TypeError: unsupported format string passed to MaskedArray.__format__
```

**Comment by bnmajor** [comment]
@joelvbernier I was unable to reproduce - Is this still an issue you are seeing? If so can you share your workflow leading up to the error?

**Comment by psavery** [comment]
It looks to me that this is the same as #752, except maybe it is an error on Windows instead of a warning (like it is on Linux).

It looks like the problem occurs when you move the mouse over a masked value in the image. Matplotlib creates masked values from `nan` and `inf` values. So if there are any `nan` or `inf` values in the raw view, this error would occur when the mouse moves over that spot.
