### ISSUE TITLE
Pixel sizes in Form View not updating properly upon change in Tree View

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#716]
I was making a detector from scratch in the GUI (single panel, but that's irrelevant) and noticed that there is a disconnect between the pixel size reported in the Form View and Tree View; it seems only the latter allows editing, and the former does not get updated after making changes in the Tree View:

![image](https://user-images.githubusercontent.com/1154130/105562845-b3893a00-5cd0-11eb-96c2-9c30572b7fe3.png)

Observe:
![image](https://user-images.githubusercontent.com/1154130/105562806-98b6c580-5cd0-11eb-99a7-ab8a20fed156.png)

**Comment by psavery** [comment]
@joelvbernier I was able to reproduce this, and it looks like it was being caused by a minimum value of "0.1" being enforced for the pixel sizes in the form view. That is why if you set a value in the tree view that is less than 0.1, it only shows "0.1" in the form view.

I relaxed this requirement (and I relaxed other min/max requirements in the form view as well) in #717, and it also uses scientific spinboxes now to allow for increased precision.
