### ISSUE TITLE
Force Euler angle convention to intrinsic zxz for LLNL workflow.

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#759]
I noticed while switching workflows in the GUI that the Load Data widget in the LLNL workflow was not computing the tilts properly -- the cause seemed to be the fact that the Euler Angle conventions had been set to "None", but the widget is expecting it to be "Intrinsic ZXZ".  As such, we should force this selection upon switching the workflow to LLNL (or at least when using the Load Data widget in that setting).

**Comment by bnmajor** [comment]
@joelvbernier This should be fixed in #762. I think the condition was leftover from the original pass at the import panel (when we only had data for TARDIS) but if there is any reason that the Euler convention should be conditional on the instrument or if this doesn't fix the issue you were seeing we can re-open this.
