### ISSUE TITLE
Sync error when updating material

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#774]
Just noticed that if I update a material interaction that forces a reinitialization (_e.g._, min d-spacing) and for which I have an activate overlay, the following things happen:

1. the exclusions get clobbered (they don't have to, but we'll have to code that fix up)
2. the `tThWidth` gets reset to the default value of 0.25°, but _does not_ update the value set in the associated attribute interaction in the overlay manager.  It _should_ adopt the value set in the overlay manager if it is specified for that material.

This may be related to other sync errors in the material package that @saransh13 is working on.

**Comment by joelvbernier** [comment]
Fixing this probably will be related to issue #767

**Comment by joelvbernier** [comment]
Also likely related: the structure factors are all coming back as 1.0:
![image](https://user-images.githubusercontent.com/1154130/109890295-eb728e00-7c3b-11eb-8e8d-0de9fa578945.png)

**Comment by psavery** [comment]
> Just noticed that if I update a material interaction that forces a reinitialization (_e.g._, min d-spacing) and for which I have an activate overlay, the following things happen:
> 
> 1. the exclusions get clobbered (they don't have to, but we'll have to code that fix up)
> 2. the `tThWidth` gets reset to the default value of 0.25°, but _does not_ update the value set in the associated attribute interaction in the overlay manager.  It _should_ adopt the value set in the overlay manager if it is specified for that material.
> 
> This may be related to other sync errors in the material package that @saransh13 is working on.

So unfortunately, calling `_newPdata()` on the material currently erases all of that info.

I've actually used a [utility function in hexrdgui](https://github.com/HEXRD/hexrdgui/blob/c4b906171a7cafdea6c9786ac8d963921a5f275f/hexrd/ui/utils.py#L90-L102) to preserve three things on new plane data creation: exclusions, tThWidth, and tThMax.

It might make sense to do this kind of thing in hexrd (maybe inside `_newPdata()`), though. Because currently, when `_newPdata()` gets called in hexrd, the exclusions, tThWidth, and tThMax get erased. Some properties such as the [`dmin setter`](https://github.com/HEXRD/hexrd/blob/9e967b145c953cb2dc37a2e3a32f4e33736919ea/hexrd/material.py#L714-L725) do this, which is why setting the `dmin` in hexrdgui erases that info.

I think inside `_newPdata()`, we can do the same kind of thing done [in the hexrdgui utility function](https://github.com/HEXRD/hexrdgui/blob/c4b906171a7cafdea6c9786ac8d963921a5f275f/hexrd/ui/utils.py#L90-L102) to preserve the exclusions, tThWidth, and tThMax. What do you guys think @joelvbernier @saransh13 ?

**Comment by psavery** [comment]
An update: I realized that re-creating the PlaneData object from scratch is probably not necessary for most, if not all, of our use cases, and it causes a performance hit when we do it.

I'm looking into removing calls to `_newPdata()`, and instead, just updating the relevant attributes on the `PlaneData` object. This work is partly being done in #791.

If we start avoiding the call to `_newPdata()` in the `dmin` setter and in the `sgnum` setter, that will hopefully fix the two original issues mentioned here.
