### ISSUE TITLE
Add snip as background method in WPPF

### ISSUE THREAD

**Issue by saransh13** [HEXRD/hexrdgui#782]
`WPPF` now has functionality to use `hexrd.imageutil.snip1d_quad` for background estimation. We need to add this to the GUI. We also discussed a way to streamline this, so we don't have to do this each time I add something to WPPF. LMK if theres something on the `hexrd` side that needs to be done for that.

**Comment by psavery** [comment]
Sure, we can add the option and widgets for snip.

About streamlining: so, if the background methods didn't require any parameters, it would be easy to automatically keep hexrdgui in sync with it. For instance, in hexrd, there could just be a list of possible background methods:
```python
background_methods = [
    'chebyshev',
    'spline',
    'snip',
]
```

We could just read this list and automatically populate the combo box with the items from the list.

If they all required one parameter of the same type (such as float), that would also be easy, as we could just use
a list like the one above and assume they all have the same number of parameters and the same type.

With varying numbers of parameters and parameter types, things start to get a little more complicated. In hexrd, we'd probably have to define a structure that provides parameter information like the following:

```python
background_methods = [
    'spline': None,
    'chevyshev': [
        {
            'label': 'Chebyshev Polynomial Degree',
            'type': int,
        }
    ],
   'snip': [
        {
            'label': 'Snip Width',
            'type': float,
        },
        {
            'label': 'Snip Num Iterations',
            'type': int,
        }  
    ],
]
```

Then in hexrdgui, we could automatically construct widgets with the label and spinbox type (or other parameter type) to match. That way, you could arbitrarily add background methods and hexrdgui would automatically create the widgets based on what is in hexrd.

If you think you might be adding a lot of background methods, then this might be a good path to go down.

PS: a dict structure like
```python
{
    'label': 'Chebyshev Polynomial Degree',
    'type': int,
}
```

Is nice mostly because it provides more flexibility in case we want to add things in the future. For example, if
you'd want to add min/max constraints, or even tooltips:
```python
{
    'label': 'Chebyshev Polynomial Degree',
    'type': int,
    'min': 0,
    'max': 99999,
    'tooltip': 'The polynomial degree used for Chebyshev.',
}
```

**Comment by saransh13** [comment]
What would be a good location to define the `background_method` dictionary you mentioned above? In the `WPPF` module itself?

**Comment by psavery** [comment]
> What would be a good location to define the `background_method` dictionary you mentioned above? In the `WPPF` module itself?

Yeah, that would be fine.
