### ISSUE TITLE
Need to have the option to apply constant offset to images on import

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#844]
As it turns out, follwoing dark subtraction we can end up with images that have negative values in them.  This causes *major* problems for SNIP and WPPF; given that we store the images as float arrays, I think that we should apply an offset (or at least provide a checkbox for the option to apply, with default `True`) to ensure the the loaded images are strictly non-negative.  can be a simple
```
img -= np.min(img)
```

**Comment by joelvbernier** [comment]
Regarding this, it would be possible to make an option in `ProcessedImageSeries` to make the images non-negative.  Since we are using that class in all of the imports, makes sense to jsut add another processing option there.  Thoughts?

**Comment by psavery** [comment]
@joelvbernier I think that sounds like a really good idea to me.

**Comment by psavery** [comment]
Just to note it here: background subtraction actually doesn't result in negative values in images because it truncates the data [here](https://github.com/HEXRD/hexrd/blob/16be327084c422acb6ac0c03a416949874aa58f5/hexrd/imageseries/process.py#L74).

Also I think we need to use [`hexrd.imageseries.stats.min`](https://github.com/HEXRD/hexrd/blob/16be327084c422acb6ac0c03a416949874aa58f5/hexrd/imageseries/stats.py#L59) to get the min of the whole image series to offset by that, rather than just the min of an individual frame.
