### ISSUE TITLE
Add option to apply pixel solid angle correction

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#851]
These arrays (same shape as detector) get applied to the raw images.  We can add a toggle in the image mode widget, since the correction can be applied in all views.  The code is a bit slow...  but necessary for some instruments.  Here is anexample from LCLS (MEC instrument):
![image](https://user-images.githubusercontent.com/1154130/112256109-bfd23a80-8c20-11eb-8d84-a41552a101e7.png)
Note that the dark subtraction is still suspect, but the relatice peak intensities are _much_ closer.  Here is the associated code (with the scaled images selected for plotting):
```
psangs = dict.fromkeys(instr.detectors)
sang_min = np.inf
sang_max = -np.inf
for det_key, panel in instr.detectors.items():
    psangs[det_key] = panel.pixel_solid_angles
    sang_min = min(sang_min, np.min(psangs[det_key]))
    sang_max = max(sang_max, np.max(psangs[det_key]))
    
scl_img_dict = dict.fromkeys(img_dict)
for det_key in scl_img_dict:
    scl_img_dict[det_key] = img_dict[det_key] / psangs[det_key]

# %%
pv = PolarView([9., 73.], instr,
               eta_min=-35, eta_max=195.,
               pixel_size=(0.025, 0.25))

# %%
pimg = pv.warp_image(scl_img_dict, pad_with_nans=True, do_interpolation=True)

# can get a properly normalized lineout (normalized by eta arclength) using 
# masked mean
lineout = np.ma.mean(pimg, axis=0)

# plotting, for your viewing pleasure
fig = plt.figure()
gs = plt.GridSpec(2, 1, figure=fig, height_ratios=(4, 1))
ax0 = plt.subplot(gs[0])
ax0.imshow(
    pimg,
    vmin=np.percentile(pimg, 50),
    vmax=np.percentile(pimg, 99),
    cmap=plt.cm.bone_r,
    extent=np.degrees(pv.extent)
)
ax0.axis('auto')
ax1 = plt.subplot(gs[1], sharex=ax0)
ax1.plot(np.degrees(pv.angular_grid[1][0, :]), np.mean(pimg, axis=0))
```
Note that the calculation of the pixel solid angles in the loop over detector panels could be done concurrently to speed the process up significantly.

**Comment by psavery** [comment]
FYI, currently, `panel.pixel_solid_angles` [is using all of the processors to run](https://github.com/HEXRD/hexrd/blob/16be327084c422acb6ac0c03a416949874aa58f5/hexrd/instrument.py#L2166).

If we run the detectors concurrently, we'll need to reduce the number of processors each `panel.pixel_solid_angles` uses or else we'll have a big slowdown with significant thrashing. As such, I'm not sure if running over the detectors concurrently will provide much of a speedup.

But if we want to go down this route, I might would recommend providing a `max_workers` kwarg to the [`PlanarDetector` initializer](https://github.com/HEXRD/hexrd/blob/16be327084c422acb6ac0c03a416949874aa58f5/hexrd/instrument.py#L1849-L1860), to basically tell it "don't use more processes than this number, because we will be running operations on the detectors concurrently".

We could then use whatever number was provided in the `pixel_solid_angles` method.

**Comment by joelvbernier** [comment]
Sounds like some testing is in order to see which is actually faster -- what do you think?  It was noticeably faster :-)
