### ISSUE TITLE
wrong image size for PXRDIP import

### ISSUE THREAD

**Issue by saransh13** [HEXRD/hexrdgui#853]
The image dimensions is wrong in the height. When I move on to the next image the dimensions get fixed, but after going to polar view, I get the Traceback which I've attached.

![output](https://user-images.githubusercontent.com/15834451/112364602-f09f8780-8c93-11eb-9624-5cad8daf953f.gif)
![Screen Shot 2021-03-24 at 11 28 31 AM](https://user-images.githubusercontent.com/15834451/112364736-1331a080-8c94-11eb-8c83-bcea0d0c15c6.png)

**Comment by joelvbernier** [comment]
@saransh13 -- fix the polar plot limits.  If you were looking at MEC, then you may need to change them.  I just imported s33335 with no issues, _but_ I had to fix the polar plot parameters (otherwise got your same error).  Not positive why the auto-calc tth pixel size was coming out to be 200 degrees...

Same shot, imported from HDF4:
![image](https://user-images.githubusercontent.com/1154130/112373676-745e7180-8c9e-11eb-9556-2032faf87b4e.png)

Could probably revisit whether or not we want the polar view parameters to be 'sticky' -- @psavery and @bnmajor, I think that they should be reset to defaults upon loading a new instrument config.  I will raise that in a separate issue though.
