### ISSUE TITLE
ERROR message from CeO2 calibration for FF HEDM

### ISSUE THREAD

**Issue by minety** [HEXRD/hexrdgui#855]
<img width="1440" alt="Screen Shot 2021-03-24 at 8 28 35 PM" src="https://user-images.githubusercontent.com/19909710/112401060-13578d80-8ce0-11eb-9cdd-7157e133ee71.png">

Another question, do I need to consider distortion (GE_41RT) when dealing with ge3 files from APS sector1?

Thanks,
Ye Tian

**Comment by psavery** [comment]
@minety We are working on that error now in #859. It happens if any of the lattice parameters are refineable (which, they are by default). You can turn off the lattice parameter refinements via the "Materials" page on the left-hand side, and clicking on "Overlay Manager", then clicking on the row of your overlay (click on the white space of the row next to the "Visible" checkbox), and unchecking the refinements for your lattice parameters, as shown below:
![image](https://user-images.githubusercontent.com/9558430/112496837-117ae200-8d53-11eb-9014-1fe1159b908f.png)

**Comment by joelvbernier** [comment]
@minety -- you'll want to make sure the lattice parameters are not refineable for the CeO2 anyhow, since this would give bad results.  We may change the default behavior to have them all unchecked (seems most reasonable @psavery) in the process of fixing the bug giving the `ValueError`.

As far as the ge3 goes, yes, you should consider the distortion.  I am going to upload a single GE CeO2 example to the [test problem repo](https://github.com/HEXRD/examples) right now.

**Comment by joelvbernier** [comment]
@minety -- this should be fixed!
