### ISSUE TITLE
The "Subtract minimum" setting is being saved and always applied to future image loading

### ISSUE THREAD

**Issue by bnmajor** [HEXRD/hexrdgui#979]
The average aggregation in the GUI is giving different intensity results than the script does for the averaging. A specific case where this can be seen is in the MEC example where the "stripes" should be zero and are currently not.

**Comment by psavery** [comment]
I haven't looked into it, but I wonder if [`average`](https://github.com/HEXRD/hexrd/blob/5e1385d163180a323d897d4e150ee8e3e4bfa4c2/hexrd/imageseries/stats.py#L88) and [`average_iter`](https://github.com/HEXRD/hexrd/blob/5e1385d163180a323d897d4e150ee8e3e4bfa4c2/hexrd/imageseries/stats.py#L97) are giving the same results.

**Comment by bnmajor** [comment]
I hadn't started on this yet either but that seems like a great starting point, thanks @psavery!

**Comment by donald-e-boyce** [comment]
I think you are proably right. I'm looking at this now.

Don

**Comment by donald-e-boyce** [comment]
I am improving the weak unittests, but here is what I found.

For a 3x5x7 array of random numbers between 0 and 20, stats.average and stats.average_iter give the same answer. But stats.average(a) and numpy.average(a, axis=0) differ on the order of 10^-6.   I am wondering if this is because we decided at the time to return results of type float32. So there is a conversion of the integer division to type float32 at the end of the functions.

**Comment by psavery** [comment]
@donald-e-boyce Thank you for looking into that! Indeed, the conversion to float32 might have caused that difference on the order of 10^-6. However, I think we are getting a much bigger difference, like some places should be 0 where they are 42, or something like that. We can dig into it more and see.

**Comment by joelvbernier** [comment]
Funny, I just ran an example (the MEC example) and find no difference between `imageseris.stats.average` and `numpy.average` on the same image stack:
```
found 18 files for detctor 'Epix10kaQuad0'
maximum diff between numpy and imageseries: 0.000000
found 18 files for detctor 'Epix10kaQuad1'
maximum diff between numpy and imageseries: 0.000000
found 18 files for detctor 'Epix10kaQuad2'
maximum diff between numpy and imageseries: 0.000000
found 18 files for detctor 'Epix10kaQuad3'
maximum diff between numpy and imageseries: 0.000000
```

code below:

```
# -*- coding: utf-8 -*-
"""
Created on Tue Jun 29 14:51:54 2021

@author: berni
"""
import copy
import glob
import os

import numpy as np

from matplotlib import pyplot as plt

from skimage import io
from scipy import ndimage

from hexrd import imageseries
from hexrd.imageseries import stats

plt.ion()
cmap = copy.copy(plt.cm.bone_r)
cmap.set_under('b')
# %%
det_names = ["Epix10kaQuad%d" % i for i in range(4)]

data_dir = "Run_150"
fname_tmpl = "Run_150_evt_*_%s.tiff"

fig1, ax1 = plt.subplots(2, 2, sharex=True, sharey=True)
fig2, ax2 = plt.subplots(2, 2, sharex=True, sharey=True)
iax, jax = np.unravel_index(range(4), (2, 2))
for i, det_name in enumerate(det_names):
    fnames = glob.glob(
        os.path.join(data_dir, fname_tmpl % det_name)
    )
    print("found %d files for detctor '%s'" % (len(fnames), det_name))
    img_stack = []
    for fname in fnames:
        # !!! these images require mirroring about the vertical (flip LR)
        img_stack.append(np.fliplr(io.imread(fname)))
    img_stack = np.stack(img_stack, axis=0)
    avg_img = np.average(img_stack, axis=0)
    avg_img_ims = stats.average(
        imageseries.open(None, format='array', data=img_stack)
    )
    print(
        "maximum diff between numpy and imageseries: %f"
        % np.max(abs(avg_img - avg_img_ims))
    )
    avg_img[avg_img < 0] = 0.
    max_img = np.max(img_stack, axis=0)
    if np.any(np.isnan(avg_img)):
        print("NaNs on %d" % det_name)
    fig1.suptitle(r"Averaged images")
    # for Epix, the gaps are identically 0, but there are some negative pixels
    # !!! generate mask using hole-filling to get only gaps
    valid_pix = ndimage.binary_fill_holes(max_img > 0)

    avg_img[~valid_pix] = -1
    this_ax = ax1[iax[i], jax[i]]
    this_ax.imshow(avg_img, vmin=0, cmap=cmap)
    this_ax.set_title(r'%s' % det_name)

    this_ax = ax2[iax[i], jax[i]]
    this_ax.imshow(valid_pix)
    this_ax.set_title(r'%s' % det_name)

    io.imsave("Run_150_avg_%s.tiff" % det_name, avg_img)
    np.save("%s_mask.npy" % det_name, valid_pix)
plt.show()
```

**Comment by joelvbernier** [comment]
FYI these data can be found [here](https://drive.google.com/drive/folders/1GXgwqWXexF94_sySHH_PP1407YfAvJz1).

**Comment by donald-e-boyce** [comment]
The difference is because all the image files are float32, and so all the
averages are the same type. If the image type is int, then the np.average
returns a double, but the stats.average returns a float32, so there is a
small difference.


...

found 18 files for detctor 'Epix10kaQuad3'

type of image file:  float32

type of image stack:  float32

type of numpy average:  float32

type of image series average:  float32

maximum diff between numpy and imageseries: 0.000000

...

**Comment by psavery** [comment]
@joelvbernier and I took a look at this issue, and it looks like it is actually being caused by the minimum being subtracted without the user knowing. If the user subtracted the minimum in a past run, it is saving that setting and always subtracting the minimum in future runs, even though the checkbox remains unchecked.

I'm going to fix this...
